apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telehealth-secrets
  namespace: telehealth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: telehealth-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: northcare/dev/telehealth/db
        property: database_url
    - secretKey: DB_PASSWORD
      remoteRef:
        key: northcare/dev/telehealth/db
        property: password
    - secretKey: VIDEO_API_KEY
      remoteRef:
        key: northcare/dev/telehealth/video
        property: api_key
