apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: {{ .Values.namespace }}
  labels:
    app: service-discovery
    app.kubernetes.io/name: service-discovery
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: northcare
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        app.kubernetes.io/name: service-discovery
      annotations:
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
        prometheus.io/path: "{{ .Values.prometheus.path }}"
    spec:
      serviceAccountName: service-discovery
      securityContext:
        runAsNonRoot: true
      containers:
        - name: service-discovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-eureka
              containerPort: 8761
              protocol: TCP
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
