{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hospital-core.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "hospital-core.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  # IRSA annotation — add the IAM role ARN in values.yaml to grant Secrets Manager access
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
