apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notifications-secrets
  namespace: notifs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: notifications-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: northcare/dev/notifications/db
        property: database_url
    - secretKey: DB_PASSWORD
      remoteRef:
        key: northcare/dev/notifications/db
        property: password
    - secretKey: TWILIO_AUTH_TOKEN
      remoteRef:
        key: northcare/dev/notifications/twilio
        property: auth_token
    - secretKey: TWILIO_ACCOUNT_SID
      remoteRef:
        key: northcare/dev/notifications/twilio
        property: account_sid
    - secretKey: SES_SMTP_PASSWORD
      remoteRef:
        key: northcare/dev/notifications/ses
        property: smtp_password
