server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/hospital/ {
        proxy_pass http://hospital-core.hospital.svc.cluster.local:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/telehealth/ {
        proxy_pass http://telehealth.telehealth.svc.cluster.local:8080/;
        proxy_set_header Host $host;
    }
    location /api/billing/ {
        proxy_pass http://billing.billing.svc.cluster.local:8080/;
        proxy_set_header Host $host;
    }
    location /api/insurance/ {
        proxy_pass http://insurance.insurance.svc.cluster.local:8080/;
        proxy_set_header Host $host;
    }
    location /api/notifications/ {
        proxy_pass http://notifications.notifs.svc.cluster.local:8080/;
        proxy_set_header Host $host;
    }
    location /api/eureka/ {
        proxy_pass http://service-discovery.discovery.svc.cluster.local:8761/;
        proxy_set_header Host $host;
        proxy_set_header Authorization "Basic ZXVyZWthLWFkbWluOm5vcnRoY2FyZS1ldXJla2EtMjAyNQ==";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
