spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/test-migration

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false

logging:
  level:
    com.northcare.notifications: DEBUG
    org.flywaydb: DEBUG

northcare:
  notifications:
    retry-delay-ms: 999999999
    scheduled-poll-ms: 999999999
