apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: northcare-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: northcare
  source:
    repoURL: https://github.com/northcare-health/gitops-argocd
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
