apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-discovery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: northcare
  source:
    repoURL: https://github.com/northcare-health/gitops-argocd
    targetRevision: HEAD
    path: service-discovery/dev
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: discovery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
