apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insurance-secrets
  namespace: insurance
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: insurance-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: northcare/dev/insurance/db
        property: database_url
    - secretKey: DB_PASSWORD
      remoteRef:
        key: northcare/dev/insurance/db
        property: password
    - secretKey: PAYER_API_KEY
      remoteRef:
        key: northcare/dev/insurance/payer
        property: api_key
