apiVersion: v2
name: ui-portal-dev
description: NorthCare UI Portal - Dev Environment Overlay
type: application
version: 0.1.0
dependencies:
  - name: ui-portal
    version: "0.1.0"
    repository: "https://github.com/northcare-health/ui-portal"
